definitions:
  model.APIStatus:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: boolean
    type: object
  model.Paging:
    properties:
      count:
        type: string
      limit:
        type: integer
      offset:
        type: integer
    type: object
  model.Result:
    properties:
      apistatus:
        $ref: '#/definitions/model.APIStatus'
      data: {}
      paging:
        $ref: '#/definitions/model.Paging'
    type: object
info:
  contact: {}
paths:
  /listAssets/{walletAddress}:
    get:
      consumes:
      - application/json
      description: |-
        fetches the assets by user wallet address
        one of the parameters walletAddress and x-wallet is mandatory and must be provided
      operationId: get-struct-array-by-string
      parameters:
      - description: Wallet Address
        in: path
        name: walletAddress
        type: string
      - description: Wallet Address
        in: header
        name: x-wallet
        type: string
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: status = true, Code = 200
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: status = true, Code = 400, Message = Provide a valid walletAddress
          schema:
            $ref: '#/definitions/model.Result'
swagger: "2.0"
